# Generated by Django 3.1.3 on 2021-10-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='LAst Name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
