# Generated by Django 3.1.3 on 2021-10-31 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_Book', '0002_auto_20211031_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Book Name',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Writer Name',
            new_name='writer_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='First Name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='LAst Name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Phone Number',
            new_name='phoneNumber',
        ),
    ]
